export const GET_NEWS_CATEGORY_INIT = 'Category/GET_NEWS_CATEGORY_INIT';
export const GET_NEWS_CATEGORY_SUCCESS = 'Category/GET_NEWS_CATEGORY_SUCCESS';
export const GET_NEWS_CATEGORY_FAILURE = 'Category/GET_NEWS_CATEGORY_FAILURE';

export const GET_CATEGORY_INIT = 'Category/GET_CATEGORY_INIT';
export const GET_CATEGORY_SUCCESS = 'Category/GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_FAILURE = 'Category/GET_CATEGORY_FAILURE';
