export const GET_NEWS_DETAIL_INIT = 'Detail/GET_NEWS_DETAIL_INIT';
export const GET_NEWS_DETAIL_SUCCESS = 'Detail/GET_NEWS_DETAIL_SUCCESS';
export const GET_NEWS_DETAIL_FAILURE = 'Detail/GET_NEWS_DETAIL_FAILURE';
